// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxav7AxpJcnbSZ6_EY2h0qIUeehRfjnGM',
    appId: '1:1059750903852:web:c2998b7bcdfb55721e9189',
    messagingSenderId: '1059750903852',
    projectId: 'flutter-chat-app-ae674',
    authDomain: 'flutter-chat-app-ae674.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ae674.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECfzPzzO3Dw_zKo9VYJupJn6k7Ssg9q0',
    appId: '1:1059750903852:android:6227c7f06532ef0f1e9189',
    messagingSenderId: '1059750903852',
    projectId: 'flutter-chat-app-ae674',
    storageBucket: 'flutter-chat-app-ae674.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeisH6vECvOmxX7ampmcuEcRdwa5tIqKs',
    appId: '1:1059750903852:ios:a206bd8e5773422a1e9189',
    messagingSenderId: '1059750903852',
    projectId: 'flutter-chat-app-ae674',
    storageBucket: 'flutter-chat-app-ae674.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeisH6vECvOmxX7ampmcuEcRdwa5tIqKs',
    appId: '1:1059750903852:ios:2376bcea406b81941e9189',
    messagingSenderId: '1059750903852',
    projectId: 'flutter-chat-app-ae674',
    storageBucket: 'flutter-chat-app-ae674.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
